name: Semver Check

on:
  push:
    paths:
      - src/**
      - Cargo.toml
      - .github/workflows/semver-check.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: obi1kenobi/cargo-semver-checks-action@v2
