name: Up-To-Date Check

on:
  # the time of this schedule is randomly generated
  schedule:
    - cron: "14 12 * * *"
  workflow_dispatch: {}
  push:
    paths:
      - generator/**
      - .github/workflows/up-to-date-check.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - uses: actions/cache@v3
        with:
          key: up-to-date-check-${{ hashFiles('generator/Cargo.lock') }}
          path: |
            generator/target
            ~/.cargo
      - working-directory: generator
        run: cargo run --release
      - run: cargo +nightly fmt
      - run: git diff
