name: Up-To-Date Check

on:
  # the time of this schedule is randomly generated
  schedule:
    - cron: "14 12 * * *"
  workflow_dispatch: {}
  push:
    paths:
      - generator/Cargo.lock
      - generator/src/**
      - generator/Cargo.toml
      - .github/workflows/up-to-date-check.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: stable
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - uses: actions/cache@v3
        with:
          key: rust-${{ steps.toolchain.outputs.rustc_hash }}-generator-${{ hashFiles('generator/Cargo.lock') }}-${{ hashFiles('generator/src/**') }}-${{ hashFiles('generator/Cargo.toml') }}
          restore-keys: |
            rust-${{ steps.toolchain.outputs.rustc_hash }}-generator-${{ hashFiles('generator/Cargo.lock') }}-${{ hashFiles('generator/src/**') }}-
            rust-${{ steps.toolchain.outputs.rustc_hash }}-generator-${{ hashFiles('generator/Cargo.lock') }}-
            rust-${{ steps.toolchain.outputs.rustc_hash }}-generator-
            rust-${{ steps.toolchain.outputs.rustc_hash }}-
            rust-
          path: |
            generator/target
            ~/.cargo
      - working-directory: generator
        run: cargo run --release
      - run: cargo +nightly fmt
      - run: git diff
